### ISSUE TITLE
#2 subtask: implement player_id-to-gamer_tag mapping

### ISSUE THREAD

**Issue by danbugs** [danbugs/smithereens#3]
I want to allow people to search results and whatnot based on their gamer tag. Considering StartGG doesn't allow searching by gamer tag (because they are not unique), I need to create a database that maps player ids (i.e., something that is searchable) to gamer tags (i.e., what I want to search by).

**Comment by danbugs** [comment]
working on it

**Comment by danbugs** [comment]
status: 
- [x] create design doc
- [x] create pidgtm db
- [x] apply migration creating player table
- [x] implement rate limit control
- [x] implement business logic:
  - [x] query pidgtm db to get latest appended player id,
  - [x] query sgg api to get player based on `curr_plaeyr_id` (i.e., last appended player id + 1), and
  - [x] append player to pidgtm db.
- [x] append player to pidgtm db.
